<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="Grpc.Net.Client"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Task1Web\Task1Web.csproj" />
    </ItemGroup>
    <ItemGroup><Protobuf Include="Protos\orders.proto" GrpcServices="Client" /></ItemGroup>

</Project>
